TOCB1107:
  TestingMode: false
  Id: "TOCB1107"
  Name: "Toán rời rạc (TOCB1107)"
  Date: "20/02/2023 8:30"
  Time: 3600
  KeyLink: "https://drive.google.com/file/d/1pnqz4zAoGvjXsYqzbuEPgq0AYdnDuSYb/view?usp=sharing"
  DocumentLink:
    TOCB1107_1:
      Code: "TOCB1107_1"
      FileName: "TOCB1107_1.pdf"
      Answers: "C D D B D A A A C B D B B C B C C A A B C A A B B D A B C A A A A B B C C A C A"
    TOCB1107_2:
      Code: "TOCB1107_2"
      FileName: "TOCB1107_2.pdf"
      Answers: "D	C	A	C	C	C	D	B	D	C B	C	C	A	B	D	C	C	C	A D	A	D	B	D	C	A	A	C	D D	D	C	B	A	D	B	C	D	B"
