KHMI1101:
  TestingMode: true
  Id: 'KHMA1101'
  Name: 'Kinh tế vĩ mô'
  Date: '14/07/2023 09:25'
  Time: 3600
  KeyLink: 'https://drive.google.com/file/d/1pnqz4zAoGvjXsYqzbuEPgq0AYdnDuSYb/view?usp=sharing'
  DocumentLink:
    KHMI1101_1:
      Code: 'KHMA1101_1'
      FileName: 'KHMI1101_1.pdf'
      Answers: 'C A B A D B D D C D A D B C D C C B B B A A D B D A D B C D A B B C A B D A A B'
KHMI1102:
  TestingMode: false
  Id: 'KHMA1102'
  Name: 'Triết học Mác - Lênin'
  Date: '14/07/2023 20:00'
  Time: 3600
  KeyLink: 'https://drive.google.com/file/d/1pnqz4zAoGvjXsYqzbuEPgq0AYdnDuSYb/view?usp=sharing'
  DocumentLink:
    KHMI1101_1:
      Code: 'KHMA1101_1'
      FileName: 'KHMI1101_1.pdf'
      Answers: 'C A B A D B D D C D A D B C D C C B B B A A D B D A D B C D A B B C A B D A A B'
KHMI1103:
  TestingMode: false
  Id: 'KHMA1103'
  Name: 'Kinh tế vĩ mô'
  Date: '24/02/2023 19:00'
  Time: 3600
  KeyLink: 'https://drive.google.com/file/d/1pnqz4zAoGvjXsYqzbuEPgq0AYdnDuSYb/view?usp=sharing'
  DocumentLink:
    KHMI1101_1:
      Code: 'KHMA1101_1'
      FileName: 'KHMI1101_1.pdf'
      Answers: 'C A B A D B D D C D A D B C D C C B B B A A D B D A D B C D A B B C A B D A A B'
KHMI1104:
  TestingMode: false
  Id: 'KHMA1104'
  Name: 'Cơ sở dữ liệu'
  Date: '15/07/2023 09:00'
  Time: 3600
  KeyLink: 'https://drive.google.com/file/d/1pnqz4zAoGvjXsYqzbuEPgq0AYdnDuSYb/view?usp=sharing'
  DocumentLink:
    KHMI1101_1:
      Code: 'KHMA1101_1'
      FileName: 'KHMI1101_1.pdf'
      Answers: 'C A B A D B D D C D A D B C D C C B B B A A D B D A D B C D A B B C A B D A A B'
KHMI1105:
  TestingMode: false
  Id: 'KHMA1105'
  Name: 'Triết học Mác - Lênin'
  Date: '15/07/2023 08:00'
  Time: 3600
  KeyLink: 'https://drive.google.com/file/d/1pnqz4zAoGvjXsYqzbuEPgq0AYdnDuSYb/view?usp=sharing'
  DocumentLink:
    KHMI1101_1:
      Code: 'KHMA1101_1'
      FileName: 'KHMI1101_1.pdf'
      Answers: 'C A B A D B D D C D A D B C D C C B B B A A D B D A D B C D A B B C A B D A A B'
KHMI1106:
  TestingMode: false
  Id: 'KHMA1106'
  Name: 'Cơ sở lập trình'
  Date: '15/07/2023 14:00'
  Time: 3600
  KeyLink: 'https://drive.google.com/file/d/1pnqz4zAoGvjXsYqzbuEPgq0AYdnDuSYb/view?usp=sharing'
  DocumentLink:
    KHMI1101_1:
      Code: 'KHMA1101_1'
      FileName: 'KHMI1101_1.pdf'
      Answers: 'C A B A D B D D C D A D B C D C C B B B A A D B D A D B C D A B B C A B D A A B'
