KHMI1101:
  TestingMode: true
  Id: "KHMI1101"
  Name: "Kinh tế vi mô (KHMI1101)"
  Date: "24/02/2023 16:00"
  Time: 3600
  KeyLink: "https://drive.google.com/file/d/1pnqz4zAoGvjXsYqzbuEPgq0AYdnDuSYb/view?usp=sharing"
  DocumentLink:
    KHMI1101_1:
      Code: "KHMI1101_1"
      FileName: "KHMI1101_1.pdf"
      Answers: "A A A C B C A C D B D B B A C C A A D A C D D B C D C C D D C B A A C B D B C B"
    KHMI1101_2:
      Code: "KHMI1101_2"
      FileName: "KHMI1101_2.pdf"
      Answers: "C C B A B C D B C D D B C C A C B D D D A B B B D A B D B C A C D B D C C A C A"
