CNTT1191:
  TestingMode: false
  Id: "CNTT1191"
  Name: "Vật lý đại cương (CNTT1191)"
  Date: "19/02/2023 14:30"
  Time: 3600
  KeyLink: "https://drive.google.com/file/d/1pnqz4zAoGvjXsYqzbuEPgq0AYdnDuSYb/view?usp=sharing"
  DocumentLink:
    CNTT1191_1:
      Code: "CNTT1191_1"
      FileName: "CNTT1191_1.pdf"
      Answers: "B C D A A D B D A C C A C B B C A A B A C B A C B C A B C B D B A A C B A A B C"
    LUCS1129_2:
      Code: "LUCS1129_2"
      FileName: "LUCS1129_2.pdf"
      Answers: "D A D C B A C C A A A B A B D C A B B C B B D A B D A C C B D A C B B C D A C D"
