CNTT1191:
  TestingMode: false
  Id: "CNTT1191"
  Name: "Vật lý đại cương (CNTT1191)"
  Date: "19/02/2023 20:00"
  Time: 3600
  KeyLink: "https://drive.google.com/file/d/1pnqz4zAoGvjXsYqzbuEPgq0AYdnDuSYb/view?usp=sharing"
  DocumentLink:
    CNTT1191_1:
      Code: "CNTT1191_1"
      FileName: "CNTT1191_1.pdf"
      Answers: "B C D A A D B D A C C A C B B C A A B A C B A C B C A B C B D B A A C B A A B C"
    CNTT1191_2:
      Code: "CNTT1191_2"
      FileName: "CNTT1191_2.pdf"
      Answers: "B D C C C D B C C A D C C A C C B B C C A B C A D D B A C A D C D C A C C B B A"
