TOCB1101:
  TestingMode: false
  Id: "TOCB1101"
  Name: "Đại số (TOCB1101)"
  Date: "13/02/2023 08:30"
  Time: 3600
  KeyLink: "https://drive.google.com/file/d/1pnqz4zAoGvjXsYqzbuEPgq0AYdnDuSYb/view?usp=sharing"
  DocumentLink:
    TOCB1101_1:
      Code: "TOCB1101_1"
      FileName: "TOCB1101_1.pdf"
      Answers: "A C B A D C A A C B C D A A B D C D A C A B C A C D D A A C B A A C A B C C B C"
    TOCB1101_2:
      Code: "TOCB1101_2"
      FileName: "TOCB1101_2.pdf"
      Answers: "C B A D D B A C C C D B D A D A B A B A A C B A C D D B A D D C C A C B C C B C"
