LUCS1129:
  TestingMode: false
  Id: "LUCS1129"
  Name: "Pháp luật đại cương (LUCS1129)"
  Date: "15/02/2023 16:00"
  Time: 3000
  KeyLink: "https://drive.google.com/file/d/1pnqz4zAoGvjXsYqzbuEPgq0AYdnDuSYb/view?usp=sharing"
  DocumentLink:
    LUCS1129_1:
      Code: "LUCS1129_1"
      FileName: "LUCS1129_1.pdf"
      Answers: "C A B D D A B A A D B A A B C D B A D D B B D A C B D C C B A A D A D B D D C C"
    LUCS1129_2:
      Code: "LUCS1129_2"
      FileName: "LUCS1129_2.pdf"
      Answers: "D A D C B A C C A A A B A B D C A B B C B B D A B D A C C B D A C B B C D A C D"
